### ISSUE TITLE
Question: how to remove upper level

### ISSUE THREAD

**Issue by meijer3** [stefandreyer/JSON-Library#4]
Hi Stefan,

I have this (simplified) model:
<pre>
TYPE MQTT_DISCOVER :
STRUCT
	name: JSONVAR;
	topic: JSONVAR;  
	device: MQTT_DEVICE;
END_STRUCT
END_TYPE
</pre>
device is another model.

I define the object like `obj:MQTT_DISCOVER`. 
It is working but it plots the keys in the json aswell, which I didn't expect nor want

<pre>
{"FB_AO_DMX_DIMMER_001":
    {
     "obj":
       {
        "name":"My Hall dimmer",
        "topic":"topic",
        "MQTT_device":
            {"device":
                { "name":null,
</pre>

How can I skip `FB_AO_DMX_DIMMER_001`, and `obj`
aswell as `MQTT_device`

So the first key is acutally `name`

**Comment by stefandreyer** [comment]
Hi,

works like desired. MaxLevel is your friend:
![image](https://user-images.githubusercontent.com/41088808/211363366-b3e25990-d524-4bbe-8623-57159f203130.png)

BR Stefan

**Comment by meijer3** [comment]
Thanks Stefan for your quick reply.  That works great for the first two keys. 
I kept playing with this but still end up with the nested key
![image](https://user-images.githubusercontent.com/45625341/211377653-8ebeb164-ebfa-4521-9016-9967e80754d2.png)

with `MaxLevel:= 1,`

**Comment by stefandreyer** [comment]
Hi,

you have one DUT to much in your struct. Please show your full eCockpit setup of the structs you want to send.

BR Stefan

**Comment by meijer3** [comment]
<pre>
TYPE MQTT_DISCOVER :
STRUCT
	baseTopic: JSONVAR; //~ 
	name: JSONVAR;
	dev_cla: JSONVAR; //device_class
	obj_id: JSONVAR; // object_id
	uniq_id: JSONVAR; //unique_id
	ic: JSONVAR; // icon
	stat_t: JSONVAR; //state_topic
	pl_on: JSONVAR; //payload_on
	pl_off: JSONVAR; //payload_off
	bri_stat_t: JSONVAR; //brightness_state_topic
	cmd_t: JSONVAR; //command_topic
	bri_cmd_t: JSONVAR; // brightness_command_topic
	bri_scl: JSONVAR; //brightness_scale
	opt: JSONVAR; //  optimistic
	on_cmd_type: JSONVAR; //on_command_type
	avty_t: JSONVAR; //availability_topic
	dev: MQTT_DEVICE;
END_STRUCT
END_TYPE
</pre>
<pre>

TYPE MQTT_DEVICE :
STRUCT
	name: JSONVAR;
	cu: JSONVAR; //configuration_url
	cns: ARRAY[1..3] OF JSONVAR; //connections 
	ids:JSONVAR; //identifiers
	mf: JSONVAR; //manufacturer
	mdl: JSONVAR; //model
	sw: JSONVAR; //sw_version
	hw: JSONVAR; //hw_version
END_STRUCT
END_TYPE

</pre>


There are two functions blocks, where I load `device` into `obj`.
<pre>
device: MQTT_DEVICE;
THIS^.device.name.CharString := LEFT(THIS^.InstanceName,iSplitLocation);
</pre>
<pre>
obj:       				MQTT_DISCOVER;
obj.dev := Device.device
</pre>

**Comment by stefandreyer** [comment]
Hi,

can you build me a test project with only this problem?

Here it works fine:

'{"baseTopic":null,"name":null,"dev_cla":null,"obj_id":null,"uniq_id":null,"ic":null,"stat_t":null,"pl_on":null,"pl_off":null,"bri_stat_t":null,"cmd_t":null,"bri_cmd_t":null,"bri_scl":null,"opt":null,"on_cmd_type":null,"avty_t":null,"dev":{"name":null,"cu":null,"cns":[null,null,null],"ids":null,"mf":null,"mdl":null,"sw":null,"hw":null}}'

BR Stefan

**Comment by meijer3** [comment]
[simple.zip](https://github.com/stefandreyer/JSON-Library/files/10376749/simple.zip)
It's probably because I defined it in two parts, in two different featureblocks.

**Comment by stefandreyer** [comment]
Hi,

can you serve a PLCopenXML export?

Do you mean "feature" or "function" block? I Don't know "feature" Blocks.

BR Stefan

**Comment by meijer3** [comment]
Sorry, yeah your right. FunctionBlocks.
The PLCopenXML is in the ZIP `simple.xml`

**Comment by meijer3** [comment]
I did initialize the device, separate. And tried to combine it when I needed it. 
It works however if I initialize both at the same time. So that works for me now.
Thanks for your time!
