### ISSUE TITLE
VariableArraySize 

### ISSUE THREAD

**Issue by meijer3** [stefandreyer/JSON-Library#5]
Hi Stefan,

I have another problem
```
THIS^.ComposeJSON(
	JSONString:= ADR(MqttJSON), 
	JSONStringSize:= SIZEOF(MqttJSON),
	JSONVars:= ADR(THIS^.HADiscoveryObj),
	NumberOfVars:= SIZEOF(THIS^.HADiscoveryObj) / SIZEOF(JSONVAR),
	MaxLevel := 1,
);

THIS^.ComposeJSON.VariableArraySize := TRUE;
THIS^.ComposeJSON.Execute := TRUE;
```
I do set `VariableArraySize` to TRUE. But the results shows still values with null. I placed the command also infront of the ComposeJSON. I am using version 15
```json
{
  "name": "Button number 009",
  "pl_on": null
} 
```
I would expect:
```json
{
  "name": "Button number 009"
} 
```

**Comment by stefandreyer** [comment]
Hi,

pl_on isn't a array:
	VariableArraySize:	BOOL;		//don't write array values which are null, resulting in variable array sizes

I faced this problem too, solved by creating 2 independent structs:
here, one with, one without transition

![image](https://user-images.githubusercontent.com/41088808/213877909-e0985e57-f3b2-4282-9854-d55b65e3bd85.png)


BR Stefan

**Comment by meijer3** [comment]
Hi Stefan, No `pl_on` isn't a array. its just a simple string.
So `VariableArraySize` should work I guess?
It is inside `FB_OUTPUT_DIMMER_MQTT.InitMqttDiscovery` :
https://github.com/MichielVanwelsenaere/HomeAutomation.CoDeSys3/blob/ff95fc08d244dfcda0c9492f0ff5f015330ecfa4/src/Exports/PLCopen.xml

**Comment by stefandreyer** [comment]
Hi,

no exactly why it ins't a array it doesn't work,

Only for elements in a array, everyting else not.

It prevents to insert a null value in the array  values:

[1,2,3,4,null,6,7,8] --> null is not beeing inserted, leading to:
[1,2,3,4,6,7,8]

BR Stefam

**Comment by meijer3** [comment]
Ah check! I was using it wrong. Thanks for your time

**Comment by meijer3** [comment]
Hi Stefan, Do you mind if I make a feature request of this?
So drop all keys with `None`/`null`
It saves quite a bit of strings in the MQTT/traffic and better for readability

**Comment by stefandreyer** [comment]
Hi,

I can write Tim a mail and make a suggestion.

BR Stefan

**Comment by meijer3** [comment]
That would help me and Michiel alot. Much appreciated!
